### ISSUE TITLE
libcublas.so.10 not found

### ISSUE THREAD

**Issue by zchrissirhcz** [aovoc/nnieqat-pytorch#2]
## Environment
Ubuntu 16.04
Miniconda installed Python3.7.3
nnieqat-pytorch, installed via git clone
NVIDIA RTX 2080, Driver Version 418.67,  Driver CUDA Version 10.1
CUDA 10.0, located in `/usr/local/cuda-10.0`

The files in `/usr/local/cuda-10.0/lib64` are:
```
libaccinj64.so                libcufftw.so             libnppc.so.10.0.130     libnppig.so.10.0.130   libnvblas.so.10.0.130
libaccinj64.so.10.0           libcufftw.so.10.0        libnppc_static.a        libnppig_static.a      libnvgraph.so
libaccinj64.so.10.0.130       libcufftw.so.10.0.145    libnppial.so            libnppim.so            libnvgraph.so.10.0
libcublas.so                  libcufftw_static.a       libnppial.so.10.0       libnppim.so.10.0       libnvgraph.so.10.0.130
libcublas.so.10               libcuinj64.so            libnppial.so.10.0.130   libnppim.so.10.0.130   libnvgraph_static.a
libcublas.so.10.0             libcuinj64.so.10.0       libnppial_static.a      libnppim_static.a      libnvjpeg.so
libcublas.so.10.0.130         libcuinj64.so.10.0.130   libnppicc.so            libnppist.so           libnvjpeg.so.10.0
libcublas_static.a            libculibos.a             libnppicc.so.10.0       libnppist.so.10.0      libnvjpeg.so.10.0.130
libcudadevrt.a                libcurand.so             libnppicc.so.10.0.130   libnppist.so.10.0.130  libnvjpeg.so.10.0.318
libcudart.so                  libcurand.so.10.0        libnppicc_static.a      libnppist_static.a     libnvjpeg_static.a
libcudart.so.10               libcurand.so.10.0.130    libnppicom.so           libnppisu.so           libnvrtc-builtins.so
libcudart.so.10.0             libcurand_static.a       libnppicom.so.10.0      libnppisu.so.10.0      libnvrtc-builtins.so.10.0
libcudart.so.10.0.130         libcusolver.so           libnppicom.so.10.0.130  libnppisu.so.10.0.130  libnvrtc-builtins.so.10.0.130
libcudart.so.10.1             libcusolver.so.10.0      libnppicom_static.a     libnppisu_static.a     libnvrtc.so
libcudart_static.a            libcusolver.so.10.0.130  libnppidei.so           libnppitc.so           libnvrtc.so.10.0
libcudnn.so                   libcusolver_static.a     libnppidei.so.10.0      libnppitc.so.10.0      libnvrtc.so.10.0.130
libcudnn.so.7                 libcusparse.so           libnppidei.so.10.0.130  libnppitc.so.10.0.130  libnvToolsExt.so
libcudnn.so.7.5.0             libcusparse.so.10.0      libnppidei_static.a     libnppitc_static.a     libnvToolsExt.so.1
libcudnn_static.a             libcusparse.so.10.0.130  libnppif.so             libnpps.so             libnvToolsExt.so.1.0.0
libcufft.so                   libcusparse_static.a     libnppif.so.10.0        libnpps.so.10.0        libOpenCL.so
libcufft.so.10.0              liblapack_static.a       libnppif.so.10.0.130    libnpps.so.10.0.130    libOpenCL.so.1
libcufft.so.10.0.145          libmetis_static.a        libnppif_static.a       libnpps_static.a       libOpenCL.so.1.1
libcufft_static.a             libnppc.so               libnppig.so             libnvblas.so           stubs
libcufft_static_nocallback.a  libnppc.so.10.0          libnppig.so.10.0        libnvblas.so.10.0
```

## To reproduce
1. build and install
```bash
git clone https://github.com/aovoc/nnieqat-pytorch
cd nnieqat-pytorch
python setup.py build
python setup.py install
```

2. write up a `test.py` file, with only one line:
```python
from nnieqat.modules import convert_layers
```

3.  `python test.py`

4. Got error message:
```
(base) zz% python test.py
Error: Please import nniepat before torch modules.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from nnieqat.modules import convert_layers
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/nnieqat-0.1.0b0-py3.7.egg/nnieqat/modules/__init__.py", line 4, in <module>
    from .linear import Linear, Bilinear
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/nnieqat-0.1.0b0-py3.7.egg/nnieqat/modules/linear.py", line 1, in <module>
    import nnieqat.gpu.quantize as Q
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/nnieqat-0.1.0b0-py3.7.egg/nnieqat/gpu/__init__.py", line 5, in <module>
    from .quantize import QuantAndDeQuantGPU, test, quant_weight, \
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/nnieqat-0.1.0b0-py3.7.egg/nnieqat/gpu/quantize.py", line 69, in <module>
    _QUANT_HANDLE = QuantAndDeQuantGPU()
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/nnieqat-0.1.0b0-py3.7.egg/nnieqat/gpu/quantize.py", line 32, in __init__
    self._libquant = ctypes.cdll.LoadLibrary(libquant_path)
  File "/home/zz/soft/miniconda3/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/home/zz/soft/miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/cuda-10.0/lib64/libcublas.so.10: version `libcublas.so.10' not found (required by /home/zz/soft/miniconda3/lib/python3.7/site-packages/nnieqat-0.1.0b0-py3.7.egg/nnieqat/gpu/lib/libgfpq_gpu.so)
```

**Comment by aovoc** [comment]
Maybe you can  install nnieqat in a docker to avoid this problems， I have updated relative installation info in ReadMe.

**Comment by zchrissirhcz** [comment]
OK, switching to cuda10.1 and that import error disappears.

**Comment by qinqiang-huihui** [comment]
you can install cudatoolkit to avoid this problems:
conda install cudatoolkit=10.2
